services:
  secprog_hw2:
    build: .
    restart: unless-stopped
    environment:
      HEADLESS_HOST: headless:5000
      HEADLESS_AUTH: supersecret
      WEB_DOM: secprog_hw2:80
    ports:
      - '127.0.0.1:8000:80'
    extra_hosts:
    - "host.docker.internal:host-gateway"

  # Headless stuff below
  headless:
    image: cybersecnatlab/challenge-headless:latest-manager
    restart: unless-stopped
    environment:
      AUTH_TOKEN: supersecret
      RABBITMQ_HOST: headless-rabbitmq
      RABBITMQ_QUEUE: headless-jobs
    depends_on:
      - headless-rabbitmq

  headless-rabbitmq:
    image: rabbitmq:3.11
    restart: unless-stopped

  headless-worker:
    image: cybersecnatlab/challenge-headless:latest-worker
    restart: unless-stopped
    environment:
      RABBITMQ_HOST: headless-rabbitmq
      RABBITMQ_QUEUE: headless-jobs
    deploy:
      replicas: 1
    depends_on:
      - headless-rabbitmq