version: "3.7"
services:
  flask_app:
    build: ./Dockerfile
    depends_on:
      - postgresql
    environment:
      - DATABASE_URL=postgresql://postgres:iotempire@postgresql:5432/postgres
    ports:
      - "80:5000"
  postgresql:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iotempire
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    name: postgres-db-vol
