apiVersion: v1
kind: Pod
metadata:
  name: first
  namespace: couzi
  labels:
    app: myfirst
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 180']

